[package]
name = "rtar"
version = "0.2.1"
authors = ["paunstefan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
